name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            args: ""
            targets: ""
            label: Ubuntu
          - os: macos-latest
            args: "--target aarch64-apple-darwin"
            targets: "aarch64-apple-darwin"
            label: macOS aarch64
          - os: macos-latest
            args: "--target x86_64-apple-darwin"
            targets: "x86_64-apple-darwin"
            label: macOS x86_64
          - os: windows-latest
            args: ""
            targets: ""
            label: Windows
    name: Tauri (${{ matrix.label }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets }}
      - uses: Swatinem/rust-cache@v2
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - run: task rdb:install-ci
      - run: task rdb:build

